### ISSUE TITLE
Performance metrics?

### ISSUE THREAD

**Issue by lukeed** [LeaVerou/bliss#120]
Read through docs & demos, looks good! 

Now interested in any performance comparisons. Are there any?
Native vs Bliss vs jQuery would be ideal, imo.

Of course, native would be fastest, but the slight performance hit from Bliss vs jQuery's steep penalty would be great to see.

**Comment by dzek69** [comment]
I'd rather see comparsion with other libraries, cause comparing this with slow-as-hell jQuery doesn't make much sense.

**Comment by lukeed** [comment]
Anything that directly proves:

1. how cumbersome jQuery is and 
2. itself as a viable jQuery replacement 

is worth it.

Since jQuery is (still) the most popular, it should be there. Any others are more than welcome to make the list. :+1:

**Comment by dzek69** [comment]
I didnt mean it shouldn't compare to jQuery. I meant I'd like to see it compare to other light solutions more, because every deleoper seeking an alternative already knows how jQuery behaves and how (almost) everything is faster ;)

**Comment by lukeed** [comment]
@dzek69 you'd be surprised :astonished:

**Comment by kurtextrem** [comment]
@dzek69's idea is good. Potential candidates: https://github.com/bendc/sprint, DOMtastic ....

**Comment by praveenpuglia** [comment]
Ok. is this right or I missed something?
http://jsperf.com/bliss-vs-iquery/2

**Comment by kurtextrem** [comment]
http://jsperf.com/bliss-vs-iquery/3
but it seems broken lol, how should jQuery be faster than native?

**Comment by dzek69** [comment]
Looks like jQuery is doing some optimizations (and uses getElementsByClassName with such simple selector instead of querySelector which is faster)

**Comment by praveenpuglia** [comment]
that's the thing! I have no idea! :o:

**Comment by dzek69** [comment]
jQuery perf impact should be the worst on complicated selectors like `#id .class[data-something]:not(.class)` - in modern browsers it will use querySelector too, but jQuery wrapper is rather heavy.

**Comment by praveenpuglia** [comment]
That's why I included vanilla `querySelectorAll` in the test too and look at the results! :O

**Comment by dzek69** [comment]
https://jsperf.com/bliss-vs-iquery/4 here, this is the most efficient way to select elements by class. the difference is H-U-G-E

**Comment by praveenpuglia** [comment]
How is Bliss slow here? so slower than jQuery? Is this fishy?

**Comment by kurtextrem** [comment]
@dzek69: Ah, thanks. My bad.

Well, Bliss is "so slow", because querySelectorAll is slow. jQuery is faster, as it selects the most efficient way to retrieve the DOM elem (but does a lot of other stuff - compare jQuery with Sprint and you'll see what I mean).

**Comment by StrongRef** [comment]
I don't get the same results using Benchmark.js locally...
I'm creating a simple performance-runner right now, where you can insert test-cases (one implementation for Bliss and one for jQuery).

```
✔ $('.notFound'); [Bliss: 1,555,769.43 ops/sec] [jQuery: 1,238,046.73 ops/sec]
✔ $('.foo'); [Bliss: 1,652,039.43 ops/sec] [jQuery: 609,581.28 ops/sec]
```

**Comment by lukeed** [comment]
@StrongRef you have to use Bliss's `$$` selector because jQuery searches for all instances of by default. `Bliss()` is a wrapper of `querySelector()`, which stops at/looks for first match.

I threw in some extra DOM selection methods to the running jsPerf file.

Also, upgraded jQuery to 2.1.4 because that version matches Bliss's minimum browser support -- equal playing field.

http://jsperf.com/bliss-vs-iquery/5

**Comment by lukeed** [comment]
@dzek69 :clap::+1: thanks for pointing that out. totally forgot about it! Will need to remember to use that method more in my own work

**Comment by LeaVerou** [comment]
Are we back to Slickspeed? Ah, the memories. 
The question is not only what is faster, but whether the difference is noticeable in any reasonable use case. E.g. caching array length in a for loop is also faster than getting `arr.length` every time, but these micro-optimizations are unncessary for 99+% of use cases.
That said, perhaps we should add hooks inside $/$$ so that people can create plugins with optimizations (like using `getElementsByClassName` when appropriate).

**Comment by StrongRef** [comment]
@lukeed I updated my post with more tests.
But why do we have to use Bliss.$?
I can't seem to find a way for jquery to perform well in those cases. There is probably a way though.

```
✔ Bliss('.many p') | jQuery('.many').first().find('p') [Bliss: 820,310.71 ops/sec] [jQuery: 210,845.25 ops/sec]
	One p within multiple nested divs
✔ Bliss('.many p') | jQuery('.many:first p') [Bliss: 830,557.89 ops/sec] [jQuery: 5,525.79 ops/sec]
	One p within multiple nested divs
```

Anyway, I was just curious about the performance because I though jQuery was performing way better but that doesn't seem to be the case.

**Comment by lukeed** [comment]
Agree with @LeaVerou's last sentence

**Comment by zdfs** [comment]
@lukeed - Do we want to keep this open? Not sure what the action item is at this point.

**Comment by lukeed** [comment]
@zdfs nah, turning into more of a StackOverflow thread type

**Comment by zdfs** [comment]
Awesome. Closing.

**Comment by kajmagnus** [comment]
F.w.i.w., I added another performance test: https://jsperf.com/blizz-vs-jquery-complicated-selector/1 — and it shows Bliss and jQuery are about the same speed, for complicated selectors (`.foo .bar .baz`).

**Comment by LeaVerou** [comment]
I believe they both use `querySelectorAll` internally so I'm not surprised.

**Comment by kajmagnus** [comment]
Yes, that was what I was expecting, mostly wanted to confirm. I've added lots of more test cases now, and really both Bliss and jQuery are super slow in comparison to the built-in functions. So I'm going to add helpers like `$byClass(...)` and `$byId(...)` to lookup elems by class & id, and have them use the built-in functions instead of Bliss or jQuery.

Here're my results:

```
Bliss('.foo .bar .baz');
47,277
±0.59%
100% slower

jQuery('.foo .bar .baz');
53,982
±0.66%
100% slower

jQuery('#theid');
2,737,562
±0.53%
93% slower

Bliss('#theid');
1,905,010
±1.17%
95% slower

Bliss('.baz');
72,188
±1.46%
100% slower

jQuery('.baz');
448,234
±0.50%
99% slower

document.getElementsByClassName('baz')
28,440,092
±0.53%
25% slower

document.getElementById('theid')
35,687,229
±0.45%
6% slower

getById('theid') custom function, just calls getElementById(..)
37,843,528
±0.52%
fastest

document.querySelectorAll('.foo .bar .baz')
69,878
±1.02%
100% slower
```

— as you can see (if you're patient and read carefully :-P ), `Bliss('.some-class')` is 6 x _slower_ than jQuery, and ... `getElementsByClassName('baz')` is 60 (!) times faster than jQuery.

So for people who really need performance, ... and perhaps if you don't want to find out if you need it or not? ... Then something like this coud make sense:

```
function $$byCss(oneSingleClass) {
  return document.getElementsByClassName(oneSingleClass);
}

function $byId(id) {
  return document.getElementById(id);
}
```
