### ISSUE TITLE
$.fetch is not well documented

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#127]
`o.sync` is not documented

**Comment by praveenpuglia** [comment]
I think the `* - Any remaining properties will be set on the XMLHttpObject directly.` declaration covers that.  Otherwise bliss has to talk about the `username` and `password` options as well which is available in `open()` via vanilla JS. 

This leads to to the idea - How about pointing to MDN pages on relevant/related APIs with in Bliss Docs? Like the `fetch()` method can have reference to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest ? @LeaVerou @zdfs - comments?

**Comment by dzek69** [comment]
on the docs it's `async` parameter, not a `sync` parameter.

async, username, password - they're not properties of xhr object and cannot be set on xhr object (at least username/password cannot). username and password can be set on the url though

**Comment by praveenpuglia** [comment]
I updated my comment above! Let me know if that makes more sense now.

**Comment by dzek69** [comment]
It makes more sense now, but as I said - you can't set username/password like that. It won't work (tested).

Also currently this method sets `o.data` on the xhr object too (also method, sync and other params we can set to set something else, not targeted for xhr object) - there is no sense in that. I don't know if this has some performance effect, but still - has no sense.

**Comment by LeaVerou** [comment]
The `sync` parameter should probably not exist at all today, as synchronous requests are deprecated in most browsers. That's why I haven't documented it. As to why it's there, probably because the first version of this helper was written years ago and I never considered removing it. Perhaps I should.
Also, please include more specific bug report titles?
