### ISSUE TITLE
scope parameter for $.each

### ISSUE THREAD

**Issue by dperrymorrow** [LeaVerou/bliss#145]
would be helpful if you could pass in the scope for the each function

```javascript
$.each([], function() {
  //...
}, this);
```

**Comment by LeaVerou** [comment]
I'd rather avoid patterns that are only needed because certain features are not yet well supported enough. In this case, arrow functions. Is there any use case of this that arrow functions wouldn't solve?
(and even if there is, it's just a matter of `.bind(this)`, which is only 5 more characters than having it as an argument.

**Comment by dperrymorrow** [comment]
fair enough, i just thought of this when i noticed this bit in bliss

```javascript
once: function(val) {
  var me = this;
  $.each(val, function(events, callback){
    //..
  });
}
```

any reason you didn't use ```.bind(this)```
polyfills to support bind seem aligned with Bliss

**Comment by LeaVerou** [comment]
No particular reason, feel free to PR it :)

I can’t wait to be able to use arrow functions in Bliss. So many times I’ve pondered using a transpiler…

**Comment by dperrymorrow** [comment]
yeah I have played around with Babel, but i kind of don't like pre-compiling js.

**Comment by LeaVerou** [comment]
I wish there was a transpiler that made the minimal amount of changes needed, e.g. maintained your formatting and everything so that you decide how different you want the two files to be depending on how many ES6 features you use.

**Comment by vlazar** [comment]
FYI since Babel 6 you turn on features you need from ES6. There is also a es2015 preset to transpile all the ES6 features.

Is there any reason to try to save formatting for transpired code?

You can think of it more like an executable code, similar to minified. There are source maps to see original nicely formatted code.

**Comment by LeaVerou** [comment]
> Is there any reason to try to save formatting for transpired code?

Preserving my code as much as possible means I can go back to it if I ever decide to, so it makes me feel less uncomfortable.

**Comment by vlazar** [comment]
I meant *transpiled of course, will never forget this word now :)
