### ISSUE TITLE
Unbind events/delegations

### ISSUE THREAD

**Issue by dzek69** [LeaVerou/bliss#156]
Documentation doesn't say a word about that. Ability to handle events as easy as in jQuery would be nice.

**Comment by LeaVerou** [comment]
Bliss does store listeners, so that would be pretty easy to implement.
Could you provide any examples of the API you would find convenient? Trying to see what exactly you're missing.
If you just want to unbind a specific event, you can always use `removeEventListener` so I assume it's mass unbinding that you're missing, right?

**Comment by dzek69** [comment]
Unbinding events requires to pass handler function, so it's not very convinient to bind with anonymous function as I cannot unbind such events without getting inside Bliss listeners storage.

I haven't thought about any specific API call example - I just need a way to do that.

A jQuery-like mechanism with ability to "name" or "group" events by "class name" and unbind events with that class name would be nice.

jQuery example:

```javascript
$('a').click(function() { /* ... */ });
$('a').bind('click.someName change.someName', function() { /* ... */ });
$('a').bind('click.someOtherName', handlerFunction);

$('a').unbind('.someName');
// two event handlers still attached, one click and one change event removed
$('a').unbind('click');
// no event handlers left
```

So maybe this should be equivalent:
```javascript
$('a')._.events({
  'click': function() {},
  'click.someName change.someName':  function() {}
  'click.someOtherName': handlerFunction
});

$('a')._.removeEvents('.someName');
// same effect as above
$('a')._.removeEvents('click');
// no events left

// This should also work:
$('a')._.removeEvents(); // will remove everything
$('a')._.removeEvents('click change'); // will remove everything in this example
$('a')._.removeEvents('click.someOtherName click.someName'); // will leave change and "classless" click event
```

**Comment by LeaVerou** [comment]
This is definitely useful functionality that I'm interested in implementing.

**Comment by LeaVerou** [comment]
Do you think this should only apply to events attached via `$.events` or also events attached via `addEventListener`? Since we wrap `addEventListener` in Bliss Full, the latter is also possible, but I’m a bit worried it might be too intrusive. Do people use periods in their event names for other reasons?

**Comment by dzek69** [comment]
PERSONALLY I would like it to work with addEventListener too. I don't know about the others. I never heard about naming events with periods. A notice in the docs would be enough for me.

**Comment by LeaVerou** [comment]
It’s actually much easier to implement that way, so that’s what I’m doing.

**Comment by dzek69** [comment]
Awesome, thanks.

**Comment by LeaVerou** [comment]
@dzek69 I pushed and added some docs :) It still needs tests though.
