### ISSUE TITLE
[website] The "fork me on github" banner is not clickable

### ISSUE THREAD

**Issue by stof** [LeaVerou/bliss#188]
This makes it very confusing.

I'm using firefox.

**Comment by dperrymorrow** [comment]
hmm, I am not able to reproduce in Firefox 46.0.1 on Mac. 
Can you give any further specifics?

**Comment by stof** [comment]
sorry, I missed some info. this is happening on the documentation page. It is working fine on the homepage

**Comment by praveenpuglia** [comment]
Ok. Here after long long time and I see that the issue comes up when you are in 90% zoom mode. Basically the **Contents** sidebar div is overlaying on top of the banner around the **Fork Me** area. Adding an explicit `z-index: 1` solves the issue. I think in any case, we would want the banner to be on top of everything.

I'll send a PR for this one and see what happens :)
