### ISSUE TITLE
Add browser support table to the readme

### ISSUE THREAD

**Issue by kurtextrem** [LeaVerou/bliss#31]
Currently, there is no clear "Which browsers are supported?". Would be great to know your intention.

For example, I've asked myself why the fetch method doesn't first check if the native fetch API is available.

**Comment by LeaVerou** [comment]
It doesn’t because then it would have to be a polyfill for the Fetch API, and it doesn’t quite follow it to the letter (mainly the object that is passed to the promise is different). Also, I’m not sure if the Fetch API is quite ready yet, at least with an XHR object there is a way to abort the request, which is still not possible with the Fetch API.
As a little historical background, `$.fetch()` evolved from the XHR helper I’ve been using for years. It just so happened that it was very similar to the Fetch API, but it was never intended as a polyfill for it. In any case, when the Fetch API is ready `$.fetch()` will likely become deprecated and then removed, unless it still offers some kind of syntactical convenience over it. But I won’t keep it around as a mere wrapper of the native API (or a polyfill), as that would be against the spirit of Bliss (which promotes polyfills over wrappers if the native API has decent usability).

**Comment by LeaVerou** [comment]
That said, there’s no browser support table, because browser support depends a lot on choice of polyfills, if any. If all needed functionality is polyfilled, it should definitely work in at least IE9.

**Comment by zdfs** [comment]
This sounds like a won't fix. Any objections.

**Comment by LeaVerou** [comment]
Not exactly a wontfix. I wouldn't be opposed at all to an interactive browser support table, where one would check polyfills and it would update automatically! :D 
But I’m not going to do it, as it's not a priority. If anyone thinks it's cool though, I will merge it and style it (i.e. whoever does it shouldn't worry about styling) :)

**Comment by zdfs** [comment]
Any takers? I'll leave it open for awhile to see if we get any bites, and if not, will close it out.

**Comment by kurtextrem** [comment]
So if I understood it correctly everything from IE9 is / should be supported?

**Comment by LeaVerou** [comment]
With polyfills, yes.

**Comment by TxHawks** [comment]
Probably too much work to maintain something like this, but since Bliss promotes polyfills over wrappers, it could be super helpful if a browser support table was included next to each method in the docs, and a polyfill for supporting said method was suggested.

**Comment by zdfs** [comment]
I'm not hearing a consensus on what people would like. I'm going to close this ticket out, but if anyone has a PR in the future addressing this problem, we'll be more than happy to take a look at it.

**Comment by kurtextrem** [comment]
Well, I thought of adding a primitive browser support table.

**Comment by zdfs** [comment]
@kurtextrem - You're more than welcome to, feel free to make a PR.
