### ISSUE TITLE
Opt for getElementById when applicable?

### ISSUE THREAD

**Issue by jcutrell** [LeaVerou/bliss#80]
In the name of optimization, would it make sense to allow the $() method to check the passed in argument to determine if getElementById is most applicable?

https://jsperf.com/getelementbyid-vs-queryselector/218

The question would be, does the checking of the argument against a regex defeat the purpose of optimizing?

**Comment by LeaVerou** [comment]
There is certainly a performance gain when using `document.getElementById()` instead, but in 99% of use cases, it's negligible. I'd rather favor readability and conciseness over premature optimization. On performance-critical use cases (e.g. if you're calling it thousands of times in a loop, or in a page with thousands of DOM elements), one can always call `document.getElementById()` directly or make their own alias. Bliss’ purpose is not to cover all possible use cases, ever, but to offer shortcuts for commonly needed things. Otherwise it will quickly grow to the same kind of volume that other generic DOM libraries have, which is exactly what we're trying to avoid here.
Hope the negative response doesn't discourage you from posting future suggestions @jcutrell! It *is* appreciated. :)
